import { ReduxProvider, ReduxPersistGate } from "@/redux/reduxProvider"
import Client from "@/app/client"
import "@/assets/scss/common.scss"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ReduxPersistGate>
            <Client>{children}</Client>
          </ReduxPersistGate>
        </ReduxProvider>
      </body>
    </html>
  )
}
