import Client from "@/app/client"
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <Client />
      </body>
    </html>
  )
}
