import { ReduxProvider, ReduxPersistGate } from "@/redux/reduxProvider"
import Client from "@/app/client"
import MswGenerator from "@repo/msw"
import "@/assets/scss/common.scss"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

function Header() {
  return <header>네비게이션</header>
}
function Footer() {
  return <footer>푸터</footer>
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <ReduxProvider>
          <ReduxPersistGate>
            <Client>
              <Header />
              {children}
              <Footer />
            </Client>
          </ReduxPersistGate>
        </ReduxProvider>
        <MswGenerator />
      </body>
    </html>
  )
}
